create extension if not exists postgis with schema extensions;

create table public.stadtteilgrenzen_geojson (
  id bigint generated by default as identity primary key,
  name text not null unique check (btrim(name) <> ''),
  nummer text not null unique check (nummer ~ '^[0-9]{2}$'),
  geometry extensions.geometry(MultiPolygon, 4326) not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint stadtteilgrenzen_geometry_valid check (extensions.st_isvalid(geometry)),
  constraint stadtteilgrenzen_geometry_not_empty check (not extensions.st_isempty(geometry))
);

create index stadtteilgrenzen_geojson_geometry_gix
  on public.stadtteilgrenzen_geojson
  using gist (geometry);

create or replace function public.set_stadtteilgrenzen_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger set_stadtteilgrenzen_updated_at
before update on public.stadtteilgrenzen_geojson
for each row execute function public.set_stadtteilgrenzen_updated_at();

alter table public.stadtteilgrenzen_geojson enable row level security;

create policy "Stadtteil boundaries are publicly readable"
  on public.stadtteilgrenzen_geojson
  for select
  to anon, authenticated
  using (true);

revoke all on table public.stadtteilgrenzen_geojson from public, anon, authenticated;
grant select on table public.stadtteilgrenzen_geojson to anon, authenticated;
grant select, insert, update, delete on table public.stadtteilgrenzen_geojson to service_role;
revoke all on sequence public.stadtteilgrenzen_geojson_id_seq from public, anon, authenticated;
grant usage, select on sequence public.stadtteilgrenzen_geojson_id_seq to service_role;

revoke all on function public.set_stadtteilgrenzen_updated_at() from public;
grant execute on function public.set_stadtteilgrenzen_updated_at() to service_role;
